version: '3.8'

services:
  billing-service:
    build:
      context: ./billing-service
    ports:
      - "9001:9001"
      - "4001:4001"
    networks:
      - internal

  user-service-db:
    image: postgres:latest
    container_name: user-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5000:5432"
    networks:
      - internal

  user-service:
    build:
      context: ./user-service
    ports:
      - "4000:4000"
    networks:
      - internal
    depends_on:
      - user-service-db
      - billing-service
    environment:
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-service-db:5432/db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=9001

networks:
  internal:
    driver: bridge
