server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: http://user-service:4000
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: api-docs-user-route
          uri: http://user-service:4000
          predicates:
            - Path=/api-docs/users
          filters:
            - RewritePath=/api-docs/users,/v3/api-docs