server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: user-service-route
          uri: http://user-service:4000
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: api-docs-user-route
          uri: http://user-service:4000
          predicates:
            - Path=/api-docs/users
          filters:
            - RewritePath=/api-docs/users,/v3/api-docs

auth:
  service:
    url: "localhost:4005"